name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "wellcome to ll"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Phase
        run: echo "running"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "Deploying the app"
