name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: | 
        echo "Wellcome to LL"
        echo "wellcome to skv"
        echo "wellcome to pos"
